version: '3'
services:
  acceptto-implementation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: acceptto-implementation
    volumes:
      - '.:/app'
      - '/app/node_modules'